<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fi" lang="fi">

<head>
	<title>Muistilista</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" type="text/css" href="main.css" />
</head>

<div id="atomik-wrapper">
<div id="atomik">
	<p>
	
	<table align="center">
	<col width="170px"/>
	<col width="130px"/>
	<col width="150px"/>	
	<col width="150px"/>
	<col width="150px"/>
	<col width="60px"/>
		<tr align="center">
		<th>Askare</th>
		<th>Luokka</th>
		<th>Luotu</th>
		<th>DL</th>
		<th>Tärkeys</th>
		</tr>
		<tr>
		<td class="noborder"></td>
		<td class="noborder"><select name="luokat">
		<option>Valitse</option>
		<option>joku luokka</option>
		</select></td>
		<td class="noborder"><input type=radio name="pvm1" value="SELECT jotain" checked>uusin ensin<br>
		<input type=radio name="pvm1" value="SELECT jotain muuta">vanhin ensin</td>
		<td class="noborder"><input type=radio name="pvm2" value="SELECT jotain">ensimmäinen ^<br>
		<input type=radio name="pvm2" value="SELECT jotain muuta">viimeinen ^</td>
		<td class="noborder"><input type=radio name="tarkeys" value="SELECT jotain">1 ensin<br>
		<input type=radio name="tarkeys" value="SELECT jotain muuta">5 ensin</td>
		</tr>
		</table>
	</p>
	<p>
	<table align="center">
	<col width="170px"/>
	<col width="130px"/>
	<col width="150px"/>	
	<col width="150px"/>
	<col width="150px"/>
	<col width="60px"/>
		<tr>
		<td>eka askare</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td class="noborder"><form><input type=image src="muokkaa.jpg" alt="Muokkaa"/>  <input type=image src="poista.jpg" alt="Poista"></form></td>
		</tr>
		<tr>
		<td>toka askare</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td class="noborder"><form><input type=image src="muokkaa.jpg" alt="Muokkaa"/>  <input type=image src="poista.jpg" alt="Poista"></form></td>
		</tr>
	</table>
	</p>
	<p></p>

	</div>

</div>
