<div id="atomik-wrapper-small">
	<div id="atomik">
	<title>Kirjautuminen</title>
	<link rel="stylesheet" type="text/css" href="main.css" />
		<h1>Kirjautuminen</h1>
		<p>
			Tervetuloa Muistilista-sovellukseen.
		</p>
		<p>
		<form action="<?php echo Atomik::url('etusivu'); ?>" method="post">
		<p>Salasana: <input type="password" name="password" value="" size="15" /> <input type=submit value="Kirjaudu"/></p>
		</form>
		</p>
	</div>
</div>
