<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fi" lang="fi">

<head>
	<title>Muistilista</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" type="text/css" href="main.css" />
</head>

<div id="atomik-wrapper-small">
<div id="atomik">

	<h2>Luokat</h2>	

	<p>
	<table align="center">
	<col width="150px"/>
	<col width="150px"/>
	<col width="60px"/>
		<tr align="center">
		<th class="noborder">Luokka</th>
		<th class="noborder">Yläluokka</th>
		</tr>
		<tr>
		<td>eka luokka</td>
		<td></td>
		<td class="noborder"><form><input type=image src="muokkaa.jpg" alt="Muokkaa"/>  <input type=image src="poista.jpg" alt="Poista"></form></td>
		</tr>
		<tr>
		<td>toka luokka</td>
		<td>tokan yläluokka</td>
		<td class="noborder"><form><input type=image src="muokkaa.jpg" alt="Muokkaa"/>  <input type=image src="poista.jpg" alt="Poista"></form></td>
		</tr>
	</table>
	</p>
	<p></p>

</div>
</div>
